{% set name = "testflo" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 293376d47216c0ced2c0fa0810e21f2aa9ad6e195af36b37c1f3bbe440655bad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - testflo = testflo.main:main

requirements:
  host:
    - pip
    - python
  run:
    - coverage <5.0.0a0
    - python
    - six

test:
  requires:
    - pip
  imports:
    - testflo
  commands:
    - testflo --help
    - testflo testflo.test -v
    - pip check

about:
  home: http://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  dev_url: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
