{% set version = "1.4.16" %}

package:
  name: testflo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testflo/testflo-{{ version }}.tar.gz
  sha256: 5fba0a741691f0add01d4c3df3b1519c7248fdabe2e224fa8286d9f4f6617aef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - testflo = testflo.main:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - coverage >=6.0
    - python >=3.5

test:
  requires:
    - pip
  imports:
    - testflo
  commands:
    - pip check
    - testflo --help

about:
  home: http://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  dev_url: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
