{% set name = "testflo" %}
{% set version = "1.4.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a52e120055b92aa46b26dc6421e6991d6b41f4cf9cdc4b208b8cbfb1019a427

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - testflo = testflo.main:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - coverage <5.0.0a0
    - python >=3.5

test:
  requires:
    - pip
  imports:
    - testflo
  commands:
    - pip check
    - testflo --help

about:
  home: http://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  dev_url: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
