{% set name = "testflo" %}
{% set version = "1.3.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a927348d49cbdb49142ff6868a0459a5ee2995f0ebc89f5bd3792e9041c17aa

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - testflo = testflo.main:main

requirements:
  host:
    - pip
    - python
  run:
    - coverage
    - python
    - six

test:
  imports:
    - testflo
  commands:
    - testflo --help
    - testflo testflo.test -v

about:
  home: http://openmdao.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  dev_url: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
