# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.4.22"
  python_check_max: "3.14"

package:
  name: testflo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/testflo/testflo-${{ version }}.tar.gz
  sha256: 2564db7eca3b87c4975cd99b8a90ad1d8274c24bbd6b5f2679626b6451aadef9

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - testflo = testflo.main:main

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - coverage >=6.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: testflo
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - testflo --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  homepage: https://pypi.org/project/testflo
  documentation: http://openmdao.org
  repository: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
