# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.4.21"

package:
  name: testflo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/testflo/testflo-${{ version }}.tar.gz
  sha256: cb3bbd6183afd97f48308dfc4eabe99d7a85e73e3fb1eb49eb6ac40fd28fcfe4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - testflo = testflo.main:main

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - coverage >=6.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: testflo
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - testflo --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A simple flow-based testing framework
  homepage: http://openmdao.org
  repository: https://github.com/OpenMDAO/testflo

extra:
  recipe-maintainers:
    - bollwyvl
