travis:
  secure:
    BINSTAR_TOKEN: JKq7Gmk9lGVK2QSDZ5Tzn40vdyxh+wL1z0qXeLwGRYNwj+cRZ8rxItp6Z8ZnjGJfkAWWBlFwnyeMtbzxnwhM+Ulv/yOcfuESwGoYZ4aOPAuXKaohND4E/8GbQf7ti3cQjupp9vUWJABdLZ/DoejLJjYwXYvYygS9Vq1bDd3fhXyuoPduqG1z8RBbK7vKD3vvtrlgqgqxUCLW9YaSnShpdnb3Nmcw/aPXUyw34Oq8yQzCKKfsjjjWKhiX+wlBHRgAr4RldRLgozwNUeIl44UWl0j8xVTYwQD/C5+6ppfKrBXaSpM9iYi7n4b6G28Azt6kPuu+TVd1h+0BCn+nGnbEX9nojBFBiDb4onkzDWiZt+cPTpdFuIewLlnRgniY5HoiwFwAJlCqxOk9y9cRoyOG3TVIkiFMZsQpiZL8BGXnG+bGi4+7TRvQHKLn19G9GIi3AMLef7s80PlOrQcAJcyh/pGjmxodkLzZaEK8U86IC713ewdS/DqUtIk5Bn09I3M9dC5jYupzbBu1GJzTsjOng32+eIBpTGtH4NlCYwLoNbGeGSYN+QsvBtX9zEX4lLpM2x2b3IR7nUtjzqUmvEEAO3XCf0iCkjBefZK5dnQSxEa7tgQycOgt4wprcSXJkCGJGCMgNzqeLOQE1VvE9EE48dd0lw6Db4YppWs5gMJs8WY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
